### ISSUE TITLE
Upgrade to Greenwood

### ISSUE THREAD

**Issue by thescientist13** [thegreenhouseio/www.thegreenhouse.io#96]
Going to see if it's possible to update my personal site to Greenwood (and Netlify) 🍀 🤞 
https://www.greenwoodjs.io/

This is a top level issue to track the overall work.
1. [x] Netlify
1. [x] ~~[CircleCi](https://circleci.com/gh/thegreenhouseio/www.thegreenhouse.io/3)~~
1. [x] [Home Page / Global Styles](#10 )
1. [x] [About Page](#99 )
1. [x] [Projects Page](#100)
1. [x] [Blog Posts](#101)
1. [x] [Google Analytics](#103) / Outbound Links
1. [x] Per (Blog Post) Page Meta data - [already being tracked](#79 )
1. [x] [Unit Testing](#102)
1. [x] Cutover DNS / merge

Notes / Observaations
1. ~~404 Page~~ being [tracked](https://github.com/thegreenhouseio/www.thegreenhouse.io/issues/112)
    - doesn't have title in `develop` mode
    - isn't serialized in `build` mode?
1. ~~Pages as custom elements?~~ - [opened issue upstream](https://github.com/ProjectEvergreen/greenwood/issues/170)
1. [Google Analytics will need extra help from Greenwood](https://github.com/thegreenhouseio/www.thegreenhouse.io/pull/111#issuecomment-522357628)
    -  being tracked: https://github.com/thegreenhouseio/www.thegreenhouse.io/issues/113
1. ~~Use `static` styles property in [`LitElement`](https://lit-element.polymer-project.org/guide/styles#static-styles)~~.  Also be aware of [`unsafeCss`](https://lit-element.polymer-project.org/guide/styles#static-styles)
    - being tracked: https://github.com/thegreenhouseio/www.thegreenhouse.io/issues/114
1. ~~Noticed outbound links in markup don't open in new link~~ - [being tracked](https://github.com/thegreenhouseio/www.thegreenhouse.io/issues/1150)

**Comment by thescientist13** [comment]
This will probably need to be done as a [plugin in Greenwood](https://github.com/ProjectEvergreen/greenwood/issues/17) since [including the GA snippet](https://developers.google.com/analytics/devguides/collection/analyticsjs/) in templates doesn't work with `LitElement`, but it does in _index.html_.

**Comment by thescientist13** [comment]
DNS working, just waiting on HTTPS to propogate
https://www.thegreenhouse.io/
